(define (make-alist! lst)
  (define (helper lst)
    (if (null? lst)
        'done
        (let ((next (cdr lst))
              (next2 (cddr lst))
              (first (car lst))
              (second (cadr lst)))
          (set-car! lst next)
          (set-cdr! lst next2)
          (set-car! next first)
          (set-cdr! next second)
          (helper next2))))
  (helper lst))