(define (make-line-obj text)
  (let ((data text))
    (lambda (msg)
      (cond ((equal? msg 'next)
             (let ((result (car data)))
               (set! data (cdr data))
               result))
            ((equal? msg 'empty?)
             (null? data))
            ((equal? msg 'put-back)
             (lambda (tt)
               (set! data (cons tt data))
               'okay))))))

