(define (interleave! lst1 lst2)
  (define (helper lst1 lst2)
    (unless (or (null? lst1)
                (null? lst2))
      (let ((remains (cdr lst1)))
        (set-cdr! lst1 lst2)
        (interleave! lst2 remains))))
  (cond ((null? lst1) lst2)
        ((null? lst2) lst1)
        (else (helper lst1 lst2)
              lst1)))
