(define (make-account balance secret)
  (let ((error-time 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define(call-the-cops)
      '110)
    (define (dispatch user-secret m)
      (if (eq? user-secret secret)
        (begin (set! error-time 0)       
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknown request: MAKE-ACCOUNT" m))))
        (begin (set! error-time (+ 1 error-time))
               (lambda (x)
                  (if (> error-time 7)
                      (call-the-cops)
                      (lambda (x) "Incorrect password"))))))
    dispatch))